apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-sec-agent.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-sec-agent.labels" . | nindent 4 }}
